# Generated by Django 5.0.4 on 2024-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecruiter",
            name="impact_score",
            field=models.FloatField(
                default=0.0,
                help_text="Calculated based on responsiveness, accuracy of job descriptions, and candidate experience.",
            ),
        ),
        migrations.AddField(
            model_name="recruiter",
            name="impact_score",
            field=models.FloatField(
                default=0.0,
                help_text="Calculated based on responsiveness, accuracy of job descriptions, and candidate experience.",
            ),
        ),
    ]
