# Generated by Django 5.0.4 on 2024-05-07 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_historicalrecruiter_impact_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrecruiter",
            name="impact_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Calculated based on responsiveness, accuracy of job descriptions, and candidate experience.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recruiter",
            name="impact_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Calculated based on responsiveness, accuracy of job descriptions, and candidate experience.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
