# Generated by Django 5.0.4 on 2024-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_recruiter_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterreview',
            name='points_awarded_for_update',
            field=models.BooleanField(default=False),
        ),
    ]
