# Generated by Django 5.0.4 on 2024-05-07 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0002_badge_level_remove_userbadge_badge_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbadge",
            name="badge",
        ),
        migrations.RemoveField(
            model_name="userbadge",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="leaderboard",
            options={
                "ordering": ["position"],
                "verbose_name": "Leaderboard Entry",
                "verbose_name_plural": "Leaderboard",
            },
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"verbose_name": "Level", "verbose_name_plural": "Levels"},
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="userlevel",
            options={
                "verbose_name": "User Level",
                "verbose_name_plural": "User Levels",
            },
        ),
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.DeleteModel(
            name="UserBadge",
        ),
    ]
